### ISSUE TITLE
Share on the FrontEnd

### ISSUE THREAD

**Issue by pagliaso** [w-vision/SocialMedia#2]
Hello,

I installed this plugin a time ago, but I am afraid I dont't understand very well how it works.

I see a user of Pimcore backend can share content, but can this be put on the website so that other people browsing the site could share content also?!

Many thanks in advance for your reply,

Alb

**Comment by aarongerig** [comment]
Hi there,

The purpose of this plugin is to share pimcore content directly onto a specific social media page of a company, an association or even a simple person. That way you don't have to copy the content and authenticate yourself in order to publish it.

If you want to make something shareable in the frontend have a look at this [link generator](http://www.sharelinkgenerator.com/).

Hope this helps!

Cheers,
Aaron

**Comment by pagliaso** [comment]
Hi Aaron,
    Many thanks for your reply and useful information.
    Thanks and kind regards from Spain,
        Alberto
    
    
    El 02/10/2017 a las 9:10, Aaron Gerig
      escribió:
    
    
      Hi there,
      The purpose of this plugin is to share pimcore content directly
        onto a specific social media page of a company, an association
        or even a simple person. That way you don't have to copy the
        content and authenticate yourself in order to publish it.
      If you want to make something shareable in the frontend have a
        look at this link generator.
      Hope this helps!
      Cheers,
        Aaron
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/w-vision/SocialMedia","title":"w-vision/SocialMedia","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/w-vision/SocialMedia"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aarongerig in #2: Hi there,\r\n\r\nThe purpose of this plugin is to share pimcore content directly onto a specific social media page of a company, an association or even a simple person. That way you don't have to copy the content and authenticate yourself in order to publish it.\r\n\r\nIf you want to make something shareable in the frontend have a look at this [link generator](http://www.sharelinkgenerator.com/).\r\n\r\nHope this helps!\r\n\r\nCheers,\r\nAaron"}],"action":{"name":"View Issue","url":"https://github.com/w-vision/SocialMedia/issues/2#issuecomment-333456482"}}}
